Yearly copyright update
Ensembl/PerlModules pull request #2
Opened 2020-01-09 15:52 UTC by tgrego

2020-01-14 11:56 UTC, ens-bwalts requested changes
There's a file called COPYING in the root of this repo that isn't commonly in other repos. It probably needs to be either updated, or removed as it looks like it might be redundant with LICENSING. @andrewyatz might be able to advise on this.

Otherwise, looks like the updater ran correctly, everything that needed updating got changed, and no files missing copyright notices.

2020-01-23 09:30 UTC, ens-bwalts requested changes
Not knowing what else to do with the COPYING file, perhaps just add
`Copyright [2018-2020] EMBL-European Bioinformatics Institute`
below the line from Genome Research Limited in COPYING and call it done?

2020-01-23 11:23 UTC, ens-bwalts approved these changes

2020-01-24 09:50 UTC, mira13 approved these changes

2020-01-24 09:50 UTC, merged